#!/usr/bin/python3


import argparse
import datetime

import colors
import optionalpha
import printing


MEGAPHONE_EMOJI = '\U0001f4e3'


def FormatEarnings(earnings_date):
  if earnings_date is None:
    return ''
  today = datetime.date.today()
  if (earnings_date - today).days < 8:
    return f'{earnings_date} {MEGAPHONE_EMOJI}'
  return str(earnings_date)


def main(args):
  headers = ['TICKER', 'IV RANK', 'PRICE', 'EARNINGS']
  widths = [6, 7, 8, 12]
  printer = printing.TabularPrinter(headers=headers, widths=widths)
  watch_list = optionalpha.GetWatchList()
  def rows():
    for item in watch_list:
      if item.rank < 30:
        paint = colors.PaintLightRed
      elif item.rank >= 30 and item.rank < 50:
        paint = colors.PaintLightYellow
      else:
        paint = colors.PaintLightCyan
      yield (paint(item.ticker),
             paint(item.rank),
             paint(item.price),
             paint(FormatEarnings(item.earnings_date)))
  printer.print(rows())


if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  args = parser.parse_args()
  main(args)
