#!/usr/bin/python3

"""Scrapes finviz.com to get the weekly and monthly volatility percentage."""


import argparse

from bs4 import BeautifulSoup
import requests


def GetHTML(ticker):
  url = 'https://finviz.com/quote.ashx?t={}&ty=c&p=d&b=1'.format(ticker)
  resp = requests.get(url)
  return resp.text


def GetVolatility(html):
  soup = BeautifulSoup(html, 'html.parser')
  elems = soup.select('table.snapshot-table2 td')
  indices = {}
  for i, elem in enumerate(elems):
    indices[elem.text.lower().strip()] = i + 1
  vol_week, vol_month = elems[indices['volatility']].text.split()
  return {'WeeklyVolatility': vol_week,
          'MonthlyVolatility': vol_month,
          'ATR': elems[indices['atr']].text,
          'Price': elems[indices['price']].text}


def main(args):
  for ticker in args.tickers:
    html = GetHTML(ticker)
    vals = GetVolatility(html)
    vals['Ticker'] = ticker
    vals['ATRPercent'] = (float(vals['ATR'])/float(vals['Price'])) * 100
    print(('{Ticker}\t'
           'VW:{WeeklyVolatility} '
           'VM:{MonthlyVolatility} '
           'ATR:{ATR} '
           'ATR%:{ATRPercent:.1f}').format(**vals))


if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('tickers', nargs='+')
  args = parser.parse_args()
  main(args)
